"""
Django settings for yoyo project.

Generated by 'django-admin startproject' using Django 1.9.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9h_jet7v7@ik$too&(=$-va-d)z8(0!=4gp9t=k8%glss8wy#+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'notebook.apps.NotebookConfig',
    'checklist.apps.ChecklistConfig',
    'web.apps.WebConfig',
    'djangobower',
    'pipeline',
    'rest_framework'
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'yoyo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "web", "templates", "web"),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'yoyo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, "static")

STATICFILES_DIRS = ()

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'djangobower.finders.BowerFinder',
    'pipeline.finders.PipelineFinder',
)

STATICFILES_STORAGE = 'pipeline.storage.PipelineStorage'

BOWER_INSTALLED_APPS = (
    'gentelella#1.1.0',
    'bootstrap-select#1.10.0'
)

PIPELINE = {
    'PIPELINE_ENABLED': True,
    'JS_COMPRESSOR' : 'pipeline.compressors.jsmin.JSMinCompressor',
    'JAVASCRIPT': {
        'web': {
            'source_filenames': (
                'gentelella/production/js/jquery.min.js',
                'gentelella/production/js/bootstrap.min.js',
                'gentelella/production/js/datatables/jquery.dataTables.min.js',
                'gentelella/production/js/datatables/dataTables.bootstrap.js',
                'gentelella/production/js/datatables/dataTables.responsive.min.js',
                'gentelella/production/js/custom.js',
                'web/js/script.js',
            ),
            'output_filename': 'web/js/web.js',
        },
    },
    'STYLESHEETS': {
        'web' : {
            'source_filenames' : (
                'gentelella/production/css/bootstrap.min.css',
                'gentelella/production/fonts/css/font-awesome.min.css',
                'gentelella/production/js/datatables/jquery.dataTables.min.css',
                'gentelella/production/js/datatables/responsive.bootstrap.min.css',
                'bootstrap-select/dist/css/bootstrap-select.min.css',
                'gentelella/production/css/custom.css',
                'web/css/style.css',
            ),
            'output_filename': 'web/css/web.css'
        }
    },
}

REST_FRAMEWORK = {
    'PAGE_SIZE': 10,
    'EXCEPTION_HANDLER': 'manager.exceptions.custom_exception_handler'
}
