# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 09:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, null=True)),
                ('done', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('date_updated', models.DateTimeField(default=datetime.datetime.now)),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklist.Checklist')),
            ],
        ),
        migrations.RemoveField(
            model_name='checklistitems',
            name='checklist',
        ),
        migrations.DeleteModel(
            name='ChecklistItems',
        ),
    ]
